name: Mirror repository

on: [push, delete, pull_request]

env:
  EXECUTABLES: 'pbrain-gomoku-ai'

jobs:
  check_program_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.14.0-dev.1911+3bf89f55c
      - name: Install kcov
        run: |
          sudo apt-get install -y kcov
      - name: Build
        run: zig build
      - name: Test
        run: zig build coverage --summary all
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true

  mirror_repository:
    runs-on: ubuntu-latest
    needs: [check_program_build_and_test]
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ secrets.REPO_MIRROR_URL }}
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.REPO_MIRROR_SSH_KEY }}
